name: Build test image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to push"
        required: true

jobs:
  image:
    runs-on: ubuntu-latest
    name: Build test image
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Registry login
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          echo $DOCKER_TOKEN | docker login --username danielflook --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build action image
        run: |
          RELEASE_TAG="${{ github.event.inputs.tag }}"

          docker buildx build \
            --build-arg FETCH_CHECKSUMS=yes \
            --build-arg VERSION="0.99.0" \
            --tag danielflook/terraform-github-actions:$RELEASE_TAG \
            --platform linux/amd64,linux/arm64 \
            --attest type=provenance,mode=max,builder-id=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID \
            --push \
            --iidfile manifest-list-digest.txt \
            image

          echo "digest=danielflook/terraform-github-actions@$(<manifest-list-digest.txt)" >> "$GITHUB_OUTPUT"
