name: Test Reaction

on: [issue_comment]

jobs:
  issue_comment:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.user.login, 'dflook') }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Plan
        uses: ./terraform-version
        with:
          path: tests/plan/no_changes
