name: Test terraform-unlock-state

on:
  - pull_request

jobs:
  default_workspace:
    runs-on: ubuntu-latest
    name: Default workspace
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check state is not locked
        uses: ./terraform-apply
        with:
          path: tests/workflows/test-unlock-state
          auto_approve: true
          variables:
            lock=false

      - name: Intentionally lock the state
        uses: ./terraform-apply
        id: failed-apply
        continue-on-error: true
        with:
          path: tests/workflows/test-unlock-state
          auto_approve: true

      # State is now locked

      - name: Check apply-failed
        run: |
          if [[ "${{ steps.failed-apply.outcome }}" != "failure" ]]; then
            echo "Apply did not fail correctly"
            exit 1
          fi

          if [[ "${{ steps.failed-apply.outputs.failure-reason }}" != "apply-failed" ]]; then
            echo "::error:: failure-reason not set correctly"
            exit 1
          fi

      # Check state-locked
      - name: Try using locked state
        uses: ./terraform-apply
        id: locked-state
        continue-on-error: true
        with:
          path: tests/workflows/test-unlock-state
          auto_approve: true

      - name: Check state locked failure-reason
        run: |
          if [[ "${{ steps.locked-state.outcome }}" != "failure" ]]; then
            echo "Apply did not fail correctly"
            exit 1
          fi

          if [[ "${{ steps.locked-state.outputs.failure-reason }}" != "state-locked" ]]; then
            echo "::error:: failure-reason not set correctly"
            exit 1
          fi
          
          echo '"${{ steps.locked-state.outputs.lock-info }}"'
          
          echo 'Lock id is ${{ fromJson(steps.locked-state.outputs.lock-info).ID }}'

      - name: Unlock the state
        uses: ./terraform-unlock-state
        continue-on-error: true
        with:
          path: tests/workflows/test-unlock-state
          lock_id: ${{ fromJson(steps.locked-state.outputs.lock-info).ID }}

      - name: Check state is not locked
        uses: ./terraform-apply
        with:
          path: tests/workflows/test-unlock-state
          auto_approve: true
          variables:
            lock=false
